### ISSUE TITLE
Cannot read property 'concat' of undefined at TokenType1

### ISSUE THREAD

**Issue by sriharikapu** [simpleledger/slpjs#19]
![image](https://user-images.githubusercontent.com/6247133/61018028-eb1ee280-a3c7-11e9-98f1-d4be1aae7a5c.png)

Encountering the following error while sending tokens.
It works sometimes and some times it doesn't work.

I would like to know the work around in implementation of this.

**Comment by jcramer** [comment]
None of the traceback shows slpjs lib, its SLP-SDK.  Please, update this issue with steps to reproduce and we will gladly reopen and try to help you.
