### ISSUE TITLE
Cannot compile in production due to some package in devDependency

### ISSUE THREAD

**Issue by anhcao142** [simpleledger/slpjs#22]
Here is what it looks like when I'm trying to compile typescript
![image](https://user-images.githubusercontent.com/5773176/67360649-b149a480-f590-11e9-9c0a-d80c133f3d58.png)

**Comment by jcramer** [comment]
What version of typescript do you have? It seems to be working fine on 3.7.2.

**Comment by jcramer** [comment]
Make sure the latest version of `bitbox-sdk` is installed.
