### ISSUE TITLE
Post Office-like state

### ISSUE THREAD

**Issue by readcash** [simpleledger/slpjs#24]
Is it possible to get a transaction into a state similar to what Vin Armani proposes with a [Post Office](https://github.com/simpleledger/slp-specifications/blob/master/slp-postage-protocol.md), i.e. to get inputs and outputs of SLP signed, then serialize the transaction to hex and unserialize it server-side, add BCH inputs to pay for the fee.

I looked at `buildRawSendTx`, it's nearly possible to build a tx with signed SLP inputs/outputs only, as I see it, but it seems that it'll throw `Error("Transaction input BCH amount is too low.  Add more BCH inputs to fund this transaction.");`, but even if that's avoidable by creating a copy of `buildRawSendTx` - let's say I serialize the TX to hex, is there a way to unserialize it from hex back to TransactionBuilder at the server-side (let's assume node.js + slp) to add the BCH inputs?

Also are there plans to support Post Offices officially in slpjs?

Any guidance would be greatly appreciated! Thank you!

**Comment by jcramer** [comment]
We could just add a flag in the `buildRawSendTx` config (e.g,. `allowLowBch`) that skips the check for the low BCH amount. Feel free to add the flag in a PR and I can review and merge it in.

For the deserialization part on the server-side to add inputs, I recommend using Bitcore.  You can see several examples where I use bitcore to deserialize transactions to add scriptSigs etc in the TransactionHelpers class.  None of the methods there will do exactly what you're looking for but you can get the idea. 
e.g., https://github.com/simpleledger/slpjs/blob/master/lib/transactionhelpers.ts#L482

I also have a bare-bones Transaction class and parser in slpjs, but it doesn't do anything with signing.  
i.e., https://github.com/simpleledger/slpjs/blob/master/lib/primatives.ts#L125

**Comment by readcash** [comment]
@jcramer Super! Thank you very much! 

Maybe it would be better to add something like `buildIncompleteTx`, so that we can skip both of those checks?

![image](https://user-images.githubusercontent.com/58006668/70032839-4b086680-15bf-11ea-8a4b-a78902b7b8e2.png)
