### ISSUE TITLE
Is simpleBchSend reliable to be used?

### ISSUE THREAD

**Issue by p0o** [simpleledger/slpjs#28]
is [simpleBchSend](https://github.com/simpleledger/slpjs/blob/master/lib/bitboxnetwork.ts#L130) function reliable to be used? I noticed it's not documented so wanted to ask if there is a reason?

I guess as far as I could understand it does not filter the utxos and should be supplied with the array item of `nonSlpUtxos` from `getAllSlpBalancesAndUtxos()`. Am I correct?

**Comment by jcramer** [comment]
That method eventually calls `slp.buildRawBchOnlyTx()` which makes sure the input TXOs have all been properly judged as `NOT_SLP`.

https://github.com/simpleledger/slpjs/blob/master/lib/slp.ts#L763

**Comment by p0o** [comment]
Thanks I will try to use it soon, should I submit a PR to add it to the readme docs?

**Comment by jcramer** [comment]
sure, a PR with example in README would be very helpful.
