### ISSUE TITLE
Can I decouple this from bitbox network?

### ISSUE THREAD

**Issue by p0o** [simpleledger/slpjs#34]
Is it possible to use the util functions in this library to judge the UTXOs that I receive from other nodes? For example from BCHD or insomnia which gives you indexed UTXOs.

**Comment by jcramer** [comment]
there's a more lightweight succinct version here: [slp-validate](https://github.com/simpleledger/slp-validate)

**Comment by p0o** [comment]
This one only validate if it's gonna burn SLPs or not? I want to get UTXOs that are non-slp, not to just validate if it's gonna burn or not. I like the function `getAllSlpBalancesAndUtxos` in this library but Bitbox is slow and I want to use faster nodes like BCHD. Is it possible?

**Comment by jcramer** [comment]
You don't need to run BitboxNetwork class, there is a BchdNetwork class.
