### ISSUE TITLE
npm install slpjs  facing errors

### ISSUE THREAD

**Issue by AqeelKazmi** [simpleledger/slpjs#36]
I have node version running 12.8.2
During installation of slpjs and all other related packages facing the following error

![image](https://user-images.githubusercontent.com/30657768/89643963-55a69880-d8d0-11ea-8d3b-587b3c148a5d.png)

Help required..

**Comment by jcramer** [comment]
Sorry, I'm not able to reproduce the error.  

To attempted to repro:
1. create a test app directory
2. `npm init`
3. `npm i slpjs`

Everything installed fine.  I am running node v12.9.1 and npm v6.10.2 but can't imagine the node version is causing the problem.
