### ISSUE TITLE
Creating NFT child tokens failing

### ISSUE THREAD

**Issue by zh** [simpleledger/slpjs#38]
Creating NFT child tokens require burning already created NFT parent token. With the current `slpjs` implementation and `bchd` node with enabled anti-burning protection this operation failing:

[Code and error message on gist.github](https://gist.github.com/zh/dee256f95a304a3c624e39b678ebc967)

Reference: seems [some additional data](https://bchd.fountainhead.cash/swagger.html#/bchrpc/SubmitTransaction) need to be filled and send to the API call

**Comment by jcramer** [comment]
This issue has been fixed in the latest version `slpjs v0.27.11` and `grpc-bchrpc-node v0.11.5`.
